[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.production.environment]
  NEXT_PUBLIC_APP_URL = "https://credchain.netlify.app"
  NEXT_PUBLIC_POLKADOT_RPC_URL = "https://rpc.polkadot.io"
  NEXT_PUBLIC_CHAIN_ID = "0x0000000000000000000000000000000000000000000000000000000000000000"
  NEXT_PUBLIC_NETWORK_NAME = "Polkadot"
  NEXT_PUBLIC_BLOCK_EXPLORER = "https://polkascan.io"
  NEXT_PUBLIC_API_BASE_URL = "https://api.credchain.io"
  NEXT_PUBLIC_WS_URL = "wss://api.credchain.io"
  NEXT_PUBLIC_KYC_ENABLED = "true"
  NEXT_PUBLIC_ML_ENABLED = "true"
  NEXT_PUBLIC_BLOCKCHAIN_ENABLED = "true"
  NEXT_PUBLIC_BLOCKCHAIN_NETWORK = "polkadot"
