[package]
name = "pallet-credit-score"
version = "0.1.0"
edition = "2021"
authors = ["CredChain Team <dev@credchain.io>"]
description = "CredChain Credit Score Pallet"
license = "MIT"

[dependencies]
# Substrate Core
sp-core = { version = "6.0.0", default-features = false }
sp-runtime = { version = "6.0.0", default-features = false }
sp-std = { version = "6.0.0", default-features = false }
sp-io = { version = "6.0.0", default-features = false }

# Frame
frame-benchmarking = { version = "4.0.0", default-features = false, optional = true }
frame-support = { version = "4.0.0", default-features = false }
frame-system = { version = "4.0.0", default-features = false }
frame-benchmarking = { version = "4.0.0", default-features = false, optional = true }

# Serde for serialization
serde = { version = "1.0", default-features = false, features = ["derive"] }

# Codec
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-io/std",
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking/std",
    "serde/std",
    "codec/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
]
