[package]
name = "credit-score-contract"
version = "1.0.0"
authors = ["CredChain Team"]
edition = "2021"

[dependencies]
ink = { version = "4.0", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []

[lib]
name = "credit_score_contract"
path = "lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "credit-score-contract"
path = "lib.rs"
