[package]
name = "pallet-oracle-integration"
version = "4.0.0"
authors = ["CredChain Team <team@credchain.io>"]
description = "Oracle Integration Pallet for CredChain"
edition = "2021"
license = "MIT"

[package.metadata]
category = "Finance"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.163", default-features = false, features = ["derive"] }

# Substrate dependencies
frame-benchmarking = { version = "4.0.0", default-features = false, optional = true }
frame-support = { version = "4.0.0", default-features = false }
frame-system = { version = "4.0.0", default-features = false }
sp-api = { version = "4.0.0", default-features = false }
sp-block-builder = { version = "4.0.0", default-features = false }
sp-consensus-aura = { version = "0.10.0", default-features = false }
sp-core = { version = "6.0.0", default-features = false }
sp-inherents = { version = "4.0.0", default-features = false }
sp-offchain = { version = "4.0.0", default-features = false }
sp-runtime = { version = "6.0.0", default-features = false }
sp-session = { version = "4.0.0", default-features = false }
sp-std = { version = "4.0.0", default-features = false }
sp-transaction-pool = { version = "4.0.0", default-features = false }
sp-version = { version = "5.0.0", default-features = false }

# External dependencies
async-trait = "0.1.68"
chrono = { version = "0.4.24", default-features = false, features = ["serde"] }
hex = "0.4.3"
jsonrpc-core = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-ws-server = "18.0.0"
log = "0.4.17"
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["full"] }
url = "2.4.0"

[features]
default = ["std"]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-oracle-integration/runtime-benchmarks",
]
std = [
    "codec/std",
    "scale-info/std",
    "serde/std",
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "sp-api/std",
    "sp-block-builder/std",
    "sp-consensus-aura/std",
    "sp-core/std",
    "sp-inherents/std",
    "sp-offchain/std",
    "sp-runtime/std",
    "sp-session/std",
    "sp-std/std",
    "sp-transaction-pool/std",
    "sp-version/std",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
    "sp-runtime/try-runtime",
]

[dev-dependencies]
sp-core = { version = "6.0.0", default-features = false }
sp-io = { version = "6.0.0", default-features = false }
